INSERT INTO blogful_articles (title, date_published,content)
VALUES
('Fish Tricks', '04/15/19','BLABLADGKHSFghjdaskjfhgvkjqwade'),
('Dog Tricks', '04/25/19','BLABLADGKHSFghjdaskjfhgvkjqwade'),
('Cat Tricks', '06/17/19','BLABLADGKHSFghjdaskjfhgvkjqwade'),
('Thoughts on pets', '07/15/19','BLAertyuuBLADGKHSFghjdaskjfhgvkjqwade'),
('Pet food', '09/25/19','BLABLAsrdtyfuibnDGKHSFghjdaskjfhgvkjqwade'),
('Pet games', '09/28/19','BLABLAasrtdyvbhjDGKHSFghjdaskjfhgvkjqwade'),
('Pretending to be pet', '10/01/19','BLABLADGwezrxtcvhjbkKHSFghjdaskjfhgvkjqwade'),
('Turnip the Beet', '10/15/19','BLAexrtcyvkhjbkBLADGKHSFghjdaskjfhgvkjqwade'),
('Stories from the unknown', '10/17/19','BLAsrtucyvhbjkBLADGKHSFghjdaskjfhgvkjqwade'),
('Burgatory', '01/15/19','BLsertduycvukbhljknABLADGKHSFghjdaskjfhgvkjqwade'),
('TMasacre', '10/15/19','BLABLADGKHSzdxfgchFghjdaskjfhgvkjqwade'),
('Kale salads', '02/25/19','BLABLADGKHSFghjdaskjfhgvkjzrextcyjgvhqwade'),
('Phylozopies', '02/15/19','BLABLADGKHSFghjdaskjfhgvkjqwadewtaresyxtcyjvgh'),
('Sandy beaches', '02/19/19','BLABLADGKHSFghjdaskjfhgvkjqwadewtaresyxtcyjvgh'),
('Vacation ideas', '02/23/19','BLABLADGKHSFghjdaskjfhgvkjqwadewtaresyxtcyjvgh'),
('Baracuda encounter', '02/28/19','BLABLADGKHSFghjdaskjfhgvkjqwadewtaresyxtcyjvgh'),
('Diving stories - Tigerfish', '03/12/19','BLABLADGKHSFghjdaskjfhgvkjqwadewtaresyxtcyjvgh'),
('Diving stories - Starfish', '02/15/19','BLABLADGKHSFghjdaskjfhgvkjqwadewtaresyxtcyjvgh')